### PR TITLE
Without PowerToys

### PR DESCRIPTION
**Pull request by ElinThePrincess**
Features:
Swapping Ctrl and Alt keys.
Smoother Alt + Tab behavior.
Suspend using Pause key.
Mimicking macOS shortcuts.
Chrome browser shortcuts.
Navigation and selection shortcuts.
Hold-to-Quit functionality.

### CODE REVIEW

**Comment by dkutsanov** [comment]
I like this version although it is for 1.x version of autohotkey. I added Win+Backspace to be able to delete one word to the left. Thanks

**Comment by ElinThePrincess** [comment]
> I like this version although it is for 1.x version of autohotkey. I added Win+Backspace to be able to delete one word to the left. Thanks

Thank you for originally creating this! I've now updated the script to AHK v2.

**Comment by dkutsanov** [comment]
> > I like this version although it is for 1.x version of autohotkey. I added Win+Backspace to be able to delete one word to the left. Thanks
> 
> Thank you for originally creating this! I've now updated the script to AHK v2.

I'm not the author of this repo 🙂 that would be @stevenilsen123

**Comment by ElinThePrincess** [comment]
> > > I like this version although it is for 1.x version of autohotkey. I added Win+Backspace to be able to delete one word to the left. Thanks
> 
> > 
> 
> > Thank you for originally creating this! I've now updated the script to AHK v2.
> 
> 
> 
> I'm not the author of this repo 🙂 that would be @stevenilsen123 

Oh, right!😅 Well, glad you liked the script:) I'm new to Github and the word of code so if you find any mistakes i'm all ears!

**Pull request closed without merging**
